### PR TITLE
Feature/bump compatible node sass

### PR DESCRIPTION
**Pull request by pichfl**
Re #32

### CODE REVIEW

**Comment by pichfl** [comment]
@n1ru4l would you mind? If you don't have time, you could add me as a collaborator here and on npm and I'll continue 🙂

**Comment by n1ru4l** [comment]
Hey I Made some annotations. I want to follow semver and your change would be a major change, If you could adjust the package.json I will merge it as soon as possible

**Comment by pichfl** [comment]
@n1ru4l I didn't see your annotations, sorry. Will update 🙂

**Comment by n1ru4l** [comment]
@pichfl This change would only be a minor change...
I am going to merge this at the end of the week.

**Comment by pichfl** [comment]
😄 now I'm a little confused. Thank you so much for bearing up with me.

**Comment by n1ru4l** [comment]
v1.1.0 release is pushed to npm

**Pull request closed without merging**
